#+TITLE: 天之下书评

我很早就关注三弦的微博了，最初连载《天之下》的时候，他会把章节放在微博上，
但是当时我没有太大的兴趣，只记得读过唐孤质问唐寡那一段。后来在微信读书上翻到，
已经是重新调整过，把《语焉不详》放在第一卷的版本了。从此就一发不可收拾。
到了现在，等待每周的更新是我平庸日常中最有规律的快乐源泉（就像《小王子》里面的狐狸）。

几个月前我去参加一个读书会，讨论的是推理小说。谈到推理小说为什么没有在中国蓬勃发展的时候，
我认为不是什么国人不喜欢逻辑推理，而是推理小说作为类型小说，在创作者和消费市场两端，
要同时跟其他类型小说竞争的，最大的对手就是武侠小说。武侠小说有文学传统、
又有武打片带起来的读者群，推理小说发展不出来不是很正常吗？但反过来说，
现在整个类型小说市场都萎缩了，武侠小说怎么能不衰落呢？作为娱乐方式，小说在感官刺激上不如影视剧，
更不用跟游戏比，甚至单纯从文字产品来说，传统类型小说甚至干不过网文。

那我们为什么还期待《天之下》？

#+BEGIN_QUOTE
对于大多数人来说，没有什么比这一点更重要，哪怕是其他艺术形式也无法与之相比。
我们是使用文字的物种。文字是智力与想象力赖以飞翔的翅膀。
音乐、舞蹈、视觉艺术、各种手工艺，所有这些对于人类的发展和幸福来说都至关重要，
没有任何一种艺术或技能是学而无用的。但如果要训练思维脱离当下实相，并带着新的认知与力量返回，
那么没有什么能够与诗歌和故事相提并论。

——厄休拉·勒古恩《操作说明》
#+END_QUOTE

厄休拉·勒古恩的此番话深得我心，文字描述的故事可以带来更多思维的深度，其他媒体可能会限制我们的想象。

那为什么是《天之下》？因为它写得好。写得好的作品才能展现一个复杂的世界，
才能拓展我们想象的空间。这也是我现在不怎么读网文和轻小说的原因——这些作品太面向市场，
一切仿佛就是为了吸引读者付账而设计的——设计，而不是创作。《天之下》写得好的地方，
最容易说的就是它的叙事节奏技巧。举例来说，第二部的重要篇章《半逼河山》（青城篇章），
是一种逢山开道遇水架桥式的节奏，问题接踵而至，每次解决问题形成一个小高潮——
紧接着就是新的问题，最后达到大高潮。最妙的时候这一卷的结尾（为了不剧透我不能描述里面的剧情），
颇有亢龙有悔的味道。而两卷之后的《貌合神离》（杨衍关外篇章），切换了另一种截然不同的节奏，
我称之为「钟摆性节奏」。角力的双方回合制进攻防守，一方进攻的时候，另一方防守，
一方攻势达到顶点的时候，就是进攻方力竭的时候，然后攻守之势逆转。写法上高明且多变，
这里我忍不住想腹诽某些当红作家，成名多年都是一套把式不断套皮，但是有失温柔敦厚之教，
就不多说了。

总之，我非常推荐大家读一下《天之下》，它现在以《语焉不详》开头，非常抓人，很容易可以读进去。
即使只是作为娱乐，也是比刷抖音视频更好的消遣方式。
