#+TITLE: x86-64 Assembly Language Programming with Ubuntu
#+OPTIONS: ^:nil
* Chap 1
简介行内容，没啥好说的。
* Chap 2
** Data Storage Size
#+CAPTION: Storage sizes
| Storage         | Size(bits) | Size(bytes) |
|-----------------+------------+-------------|
| Byte            | 8-bits     | 1 byte      |
| Word            | 16-bits    | 2 bytes     |
| Double-word     | 32-bits    | 4 bytes     |
| Quadword        | 64-bits    | 8 bytes     |
| Double quadword | 128-bits   | 16 bytes    |

#+CAPTION: C/C++ data type sizes
| C/C++ Declaration | Storage     | Size(bits) | Size(bytes) |
|-------------------+-------------+------------+-------------|
| char              | Byte        | 8-bits     | 1 byte      |
| short             | Word        | 16-bits    | 2 bytes     |
| int               | Double-word | 32-bits    | 4 bytes     |
| unsigned int      | Double-word | 32-bits    | 4 bytes     |
| long              | Quadword    | 64-bits    | 8 bytes     |
| long long         | Quadword    | 64-bits    | 8 bytes     |
| char *            | Quadword    | 64-bits    | 8 bytes     |
| int *             | Quadword    | 64-bits    | 8 bytes     |
| float             | Double-word | 32-bits    | 4 bytes     |
| double            | Quadword    | 64-bits    | 8 bytes     |

** CPU

ALU: Arithmetic Logic Unit 算术和逻辑单元。

*** 寄存器

**** GPRs 通用寄存器
#+CAPTION: 通用寄存器
| 64-bit | 低位32-bit | 低位16-bit | 低位8-bit |
|--------+------------+------------+-----------|
| rax    | eax        | ax         | al        |
| rbx    | ebx        | bx         | bl        |
| rcx    | ecx        | cx         | cl        |
| rdx    | edx        | dx         | dl        |
| rsi    | esi        | si         | sil       |
| rdi    | edi        | di         | dil       |
| rbp    | ebp        | bp         | bpl       |
| rsp    | esp        | sp         | spl       |
| r8     | r8d        | r8w        | r8b       |
| r9     | r9d        | r9w        | r9b       |
| r10    | r10d       | r10w       | r10b      |
| r11    | r11d       | r11w       | r11b      |
| r12    | r12d       | r12w       | r12b      |
| r13    |            |            |           |
| r14    |            |            |           |
| r15    |            |            |           |

#+CAPTION: rax 可视化
#+BEGIN_EXAMPLE
                                     /               eax                \
rax = |******************************|****************|********|********|
                                                      \   ah   /\   al  /
						      \        ax       /
#+END_EXAMPLE

**** RSP: 栈寄存器
保存栈顶。

**** RBP: 基指针寄存器

**** RIP: 指令指针寄存器
指向下一条要执行指令的指针。

**** rFlags: Flag 寄存器和存储器
转台喝 CPU 控制信息。

**** XMM 寄存器

*** 缓存
一级缓存和二级缓存。
*** 主存
主存可以看成连续的 bytes。

#+CAPTION: 小存储 2byte 实例
#+BEGIN_EXAMPLE
|15|14|13|12|11|10|9|8|7|6|5|4|3|2|2|0|
|     MSB             |       LSB     |
#+END_EXAMPLE
** 存储
#+CAPTION: 程序内存
#+BEGIN_EXAMPLE
high    =====================
              stack              自顶向下
	        .
		.
		.
	       heap              heap 动态申请的数据(alloc)
	=====================
	BSS - uninitialized data 未初始化数据段
	=====================
	       data              initialized data(汇编阶段被初始化的值)
	=====================
	     text(code)          machine language
	=====================
	      reserved           not available to user programs
low 	=====================
#+END_EXAMPLE
** memory hierarchy
* chap 3
** 整数表示
补码。
** 有符号和无符号运算
** 浮点数
浮点数运算。
** 字符与字符串
* chap 4
定义常量：
#+BEGIN_SRC asm
  <name>	equ	<value>
#+END_SRC

在 data 段定义初始化变量
#+BEGIN_SRC asm
  <varName>	<dataType>	<initValue>
#+END_SRC
#+CAPTION: data 段定义
#+BEGIN_EXAMPLE
bVar db 10
#+END_EXAMPLE

在 BSS 段定义未初始化变量
#+BEGIN_SRC asm
  <variableName>    <resType>     <count>
#+END_SRC
#+CAPTION: 在 BSS 段定义 array
#+BEGIN_EXAMPLE
bArr resb 10
#+END_EXAMPLE
* chap 5
** Assemble/Link/Load

#+BEGIN_EXAMPLE
+------------+     /----------\      +-------------+     /------\     +------------+
|source file |---> | Assemble |----->| Object File |---->| Link |---->| Executable |
+------------+     \----------/      +-------------+     \------/     +------------+
#+END_EXAMPLE
Loader 不用关心。

这一章讲 list 信息的内容还要结合别的实例代码看看
* chap 6
Debugger ，跳过。
* chap 7
指令集简介
** 7.2 - 7.4 Data Movement
这部分主要的指令是 ~mov~:
#+BEGIN_SRC asm
  mov eax, dword [myVar] ; dword 是长度，
  mov <desc>, <src>	
#+END_SRC
如果要从内存读取值，需要~[]~:
#+BEGIN_SRC asm
  mov rax, qword [var1] ; 将 var1 的值读到 rax
  mov rax, var1         ; 将 var1 的地址读到 rax	  
#+END_SRC
读内存地址有另外一个指令：
#+BEGIN_SRC asm
  lea <reg64>, <mem>
#+END_SRC
最后是一些涉及转换的内容，比如从 quadword 读一个 byte 到另外一个寄存器。
从大到小的转换要小心截断。
#+CAPTION: 截断示例
#+BEGIN_SRC asm
  mov rax, 500
  mov byte [bVal], al	
#+END_SRC

从小到大的转换主要是要区分有符号和无符号，无符号填0即可，有符号需要根据符号选择填0或者填1.
** 7.5 Integer Arithmetic Instructions
#+BEGIN_SRC asm
  add <dest>, <src> ; <dest> = <dest> + <src>
  inc <operand>	  
#+END_SRC
两边长度要对齐。

特殊情况是进位：
#+BEGIN_SRC asm
  adc <dest>, <src> ; <dest> = <dest> + <src> + <carryBit>
#+END_SRC

carryBit 放在 rFlag 寄存器里面。

减法与加法类似，不过我不知道如果减出负数来怎么办我并不知道。

无符号乘法的独特之处是，其中一个乘数在哪个寄存器里面，是根据另一个乘数的长度决定的，总的来说，都在 A 系列的寄存器里面。

#+BEGIN_SRC asm
  mul <op8>  ; ax = al * <src>
  mul <op16> ; dx:ax = ax * <src>
  mul <op32> ; edx:eax = eax * <src>
  mul <op64> ; rdx:rax = rax * <src>
#+END_SRC

有符号乘法可以像无符号乘法一样，就一个乘数。但是也可以加上 <desc>.

除法没有深入，商和余数会放在不同的寄存器，也是会根据除数的长度有变化。
** 7.6 逻辑运算
~xor~, ~and~, ~or~ 都不能是内存，dest 也不能是 imm。

~not~ 的 operand 也不能是 imm.

逻辑左移/右移 ~shl~ / ~shr~ 没啥很特别的，就是记住，左移是乘2，右移是除2.

但是算术左移感觉跟逻辑左移没有区别，右移有个重要的点是：要保持符号位不变。

rotate 这个运算我就不知道它实际有什么作用。
** 7.7 控制语句
最基本的是 label ，和无条件跳转。
#+BEGIN_SRC asm
  jump <lable>
  
<label>:
  xxx
  xxx
#+END_SRC

然后是 condition jmp 指令，它有两部分：compare 部分会把比较结果放在 rFlag 寄存器里面，
然后 condition jmp 跳转到对应的 label。
#+BEGIN_SRC
  cmp eax, 3 ; compare eax with 3
  je <label> ; if <op1> == <op2>, jump to <label>
#+END_SRC

循环可以用 condition jump 实现。但是可以用 ~loop~:
#+BEGIN_SRC
  loop <label>
  ;;
  dec rcx
  cmp rcx, 0
  jne <label>
#+END_SRC

简而言之，~loop~ 固定使用 rcx 递减实现了条件跳转。
* chap 8
register mode, imm mode 都没有什么可以说的，memory mode 会有点麻烦，
因为会有取值和取地址的区别。

列表取值需要注意，前进的步长需要由列表 size 调整。

#+CAPTION: Size and step 
| Size        | Size(bytes) |
|-------------+-------------|
| byte        |           1 |
| word        |           2 |
| double-word |           4 |
| quadword    |           8 |
* chap 9
栈就两个指令，用到 rsp 寄存器：

#+BEGIN_SRC asm
  push <op64>  ; rsp dec 8(1 quadword), set rsp's value to be operand
  pop <op64>   ; set operand to be rsp's value, rsp inc 8
#+END_SRC
* chap 10
程序开发就都是老话了。
* chap 11
这一章有价值的就是单行宏和多项宏定义的方式。
#+CAPTION: 单行宏
#+BEGIN_SRC asm
  %define mulby4(x)  shl x, 2

  mulby4(rax)
#+END_SRC

#+CAPTION: 多行宏
#+BEGIN_SRC
  %macro <name> <number of args>
    ; [body]
  %endmacro
#+END_SRC
引用参数用 ~%<number>~ 从1开始。
