#+TITLE: 年度书单其一
#+AUTHOR: Dantezy <zhangyet@gmail.com>
#+HTML_HEAD: <link rel="stylesheet" href="https://latex.now.sh/style.css">
#+OPTIONS: ^:nil

一眨眼就到年底了，各个软件网站都会出年度总结了，作为一个读书播客，我是不是也该出个年度书单呢？很惭愧，出不了。马伯庸老师最近在他的公众号里面发了他的年度书单，这篇公众号文章叫《沉静与蓄积——我的2025年书单》。这个书单挺有意思的，大家可以去看一下。

我翻了一下今年的豆瓣，到写稿的时候我标注了95本读过，当然这可能不准，有些书是我之前读完忘记标，所以最近才标上。不过这不重要，里面有很多书都是草草了事，不特意翻一下我都忘记曾经读过。这一期我就从今年读过的书里面挑一些有意思的书来聊一下。

我今年第一本标识读完的书是劳伦斯·布洛克的《漫步死亡之地》，是马修·斯卡德系列，它有另外一个译名叫《行过死荫之地》，这个名字来自《圣经·诗篇》：「我虽然行过死荫的幽谷，也不怕遭害，因为你与我同在」。我更喜欢这个译名，我们后文就用这个名字好了。这本《行过死荫之地》是一本侦探小说，其实侦探小说跟推理小说应该分开来看。如果一个读者从东野圭吾出发，看日式推理小说，尤其是偏向本格一流作品的话，他再过来看这本《行过死荫之地》，或者其他劳伦斯·布洛克的作品，可能都不习惯。从福尔摩斯开始，推理小说很多时候塑造的都是安乐椅神探，他不需要亲自调查，只需要检查所有收集到的证据，就能靠推理推断真相。后来日本的本格派很多也是走这种路线。但马修·斯卡德不是这种侦探，他破案靠的是「抬起屁股去敲门」(Get Off Your Ass and Knock on Doors)，读这一系列的小说，你尝尝看到他穿行在纽约的大街小巷，挨个问有没有目击证人，有没有情报，最后的推断很简单，写成代码可能就是几个 if-else 的事情。

我现在看日式推理小说，总有一种感觉，就是这些小说都在尝试构造一个过火的诡计，然后用故事包裹这个诡计。诡计是核心，故事这是用来凑字数算稿费的，阅读这种小说的乐趣是猜谜。但劳伦斯·布洛克这类硬汉派的侦探小说核心是侦探，他们会塑造一个有血有肉的侦探。我跟马修·斯卡德很熟，我知道他曾经在纽约当警察，离了婚，孩子跟了前妻。离开警队之后很长一段时间他在纽约一家酒店长租了一个房间，住在那里。他一度酗酒，加入了匿名酗酒会，后来成功戒酒。他有个曾经当过应召女郎的女友伊莱恩，后来同居了（我不知道有没有结婚）。读马修·斯卡德的小说感觉就是在读一个熟人的故事，很适合在冬天天气冷天黑得早的时候随意读一下，可以随时开始随时放下。

第二本标识的书是《伊朗四千年》。今年伊朗日子不太好，但我读这本书不是因为后来伊朗跟以色列的事情。是因为我认识了一个伊朗网友，我这个播客的封面也是后来拜托这个网友重新设计了的。有这个因缘在，所以我想更了解一点伊朗。我读完之后想整理一个年表，但还没有整理完。其实应该一边读一边整理的。我后来读了《托尔金传》也是这样，想整理一份托尔金年谱，至今没有完成。

伊朗的历史，悠久，而且复杂，里面很多人名太长我记不住。历史上它跟罗马的互动很多，我觉得不了解伊朗，或者说波斯帝国的历史，也难以了解罗马的历史。回头还是应该继续去整理这个年表，等整理完了可能会做一期节目。

我对于中国没有赶上工业革命感到很惋惜。对于这个问题，我也想了很多，不是很成熟，基本的框架是这样的，中国从轴心时代开始，是长于理性短于理论，这一点是读了陈嘉映先生那本《哲学·科学·常识》之后修正的。然后还有个问题就是中国古代和希腊-罗马、还有波斯这些原生文明的交流强度不够。这两个缺陷，尤其是后者，才是关键。但伊朗的历史让我这个理论变得漏洞百出，因为它在这么四战之地，不断和罗马以及欧洲的文明争战，最后在工业革命的浪潮里面也是慢了好几拍。我这个理论因为伊朗的存在基本上就算是破产了，幸好我不用评文科一级教授。

我今年买了文石的 Leaf3C 电纸书阅读器，买了之后我在上面读了卢昌海老师的几本书，第一本就是《黎曼猜想漫谈》，里面的公式在 Leaf3C 上显示得很好。说到这个我要扯一点题外话，我觉得现在中文电子书籍的排版还是很糟糕，理工科的书一遇到公式就是贴图，这个图往往还不是矢量图，在文字环绕下非常突兀，甚至很多编程相关的书，源代码伪代码也是贴图，很难看。

黎曼猜想本身不好谈，它涉及复变函数、无穷级数等一堆很专业的概念，不用数学公式根本说不清，而且到了二十世纪后期那些发展，都太专业，没有什么科普的余地。卢老师也只能想不要钱那样写数学公式。黎曼猜想可能还好一点，它前面有一个清晰的故事线。有很多现代的科学进展很难找到一个完整的故事。我读完这本之后还读了卢老师关于天文学的科普《寻找太阳系的疆界》，这本书我对里面的故事不是很感兴趣，倒是很想知道，当年欧洲的科学家他们怎样记录行星的轨迹，并且可以互相交流？数学家们又是怎样用这些数据去算一个公式？我后来有搜了一下，用地平座标可以搜到一些更进一步的科普视频，大家可以了解一下。

到三月份就，我读完了《百年孤独》。《百年孤独》当然很了不起，但我作为比较资深的豆瓣用户，这些年我深刻体会到一件事，读一本很了不起的书不会让你变得了不起。关于《百年孤独》我觉得没什么可以说的，梁文道有一期节目讲了《百年孤独》，大家去听这个节目就行了。很多人对《百年孤独》望而却步，原因有两个，第一是觉得人名长，这个障碍建议去读一下俄罗斯小说，「阿列克塞·费尧多罗维奇·卡拉马佐夫是我县一位地主费尧多尔·巴普洛维奇·卡拉马佐夫的第三个儿子。」读完回来觉得南美名字不过如此。第二就是人物关系复杂，而且重名的人太多，这个也不用担心，因为里面出场的人物很遵循局部性，同一个情节里面出现的人物不多，你只要顺着读下去，很少会出现分不清谁是谁的情况。我没什么可以评论的，但是我可以帮大家破掉关于《百年孤独》的谜障。不得不感叹，新加坡还真的特别适合读《百年孤独》，潮湿、闷热，最近还是讨厌的雨季——而且，别忘了上校的导师梅尔基亚德斯就是病死在新加坡的沙洲上的。

想不到翻了一下豆瓣的记录，一下子就聊了这么多，看来光是今年的书单都能做三到四期节目。
