#+TITLE: 常识：我想谈谈公共知识分子
#+AUTHOR: Dantezy <zhangyet@gmail.com>
#+HTML_HEAD: <link rel="stylesheet" href="https://latex.now.sh/style.css">
#+OPTIONS: ^:nil

如果大家有留意过本节目最初的十几期，以及第一期更新的日期，大家都会知道本节目是在蹭谁的流量。没听过没关系，其实大家看节目名字就知道。
既然如此，我其实是有义务去讲一下这个被蹭了那么久热度的公共知识分子梁某道的书。我这么称呼道长不是因为我不尊重他，是因为之前被审核卡了一次，
我就不再冒这个险了。

我们今天来讲道长的时评合集，《常识》。《常识》这本书出版在2009年，一眨眼十五年就过去了。道长在自序里面说：

#+BEGIN_QUOTE
*除非你是梁启超，有一支生花妙笔，能够痛快淋漓地把四万万人的心底话都写出来，或者是林行止，香江第一健笔，能日日笔耕，每年一本集子恰恰就是整个时代的记录；否则，把时事评论结册出书又有什么意义呢？*
#+END_QUOTE

时事评论是因时事而生的，当时移世易，当初的时事背景已然不在，所谓皮之不存毛将焉附，那时事评论还怎能自立？

所以道长说：

#+BEGIN_QUOTE
*只有一种情况能使时事评论不朽，那就是你说的那些事老是重复出现。……任何有良心的评论家都该期盼自己的文章失效，他的文章若是总有现实意义，那是种悲哀。除非他那作者的自我要大于一个知识分子的志趣；江山不幸诗家幸。*
#+END_QUOTE

那《常识》过时了吗？我不能不老土地说一句，这取决于你怎样看。如果你去微信读书看《常识》下面的划线，那这十五年我们可以说是原地踏步，毫无进步。

我也检点了其中一些章节，仔细检查了一些当年评论，对比了一下今昔。比如说一篇《万众一心，异议的消失》，里面说到：
#+BEGIN_QUOTE

*没有人只想“空谈”​，问题是除了为救灾工作打气，除了以言语表达哀思之外，绝大部分的人还可以说些什么呢？人的思维广阔，几至无限；而言论的表述则是此无限思维的直接产物。要他们不在这时候说出他们想说的话，某程度上就是要求大家只能用一种思维方式去体现“万众一心”的崇高。*

*然而，谁去界定万众一心暂停差异的合理时刻呢？基于什么标准？所谓的“万众一心”又该怎么个“一心”法呢？*
#+END_QUOTE

这一篇我心有戚戚焉，别的地方我不太熟，但中文互联网往往是这样的，一旦形成一个舆论热点，占据上风的一方就呼朋引伴占据道德高地，直接不审而判剥夺异议者的发言权。
这已经不是「跟以前一样」了，这是世风日下了。

但我们的世界真的就这么糟糕吗？这还真不是，前面自序里面提到矿难，我记得那个时候矿难的新闻很多。梁文道在自序里面说：
#+BEGIN_QUOTE

*几年前发生过矿难，评论家费煞苦心地分析它的成因，推介善后的处置，指出杜绝它再度发生的方法。结果它不只没有消失，反而更加频密地发生。*
#+END_QUOTE

但是我查了维基百科，中国矿难列表里面的统计，21世纪中国的矿难死亡人数从2002年最高峰6995人下降到2022年518人，之后没有更新的统计数据。
当然如果你质疑这个数字是官方作假， 那我没有什么可以说的。我并没有精力去找资料作交叉认证。同时我要说一下，中国解决矿难的方法，估计不会是道长喜欢的。

另外这本书里面有很多内容跟灾难有关，我们当时都知道2008年有汶川大地震，所以集子里面出现了很多跟灾难相关的内容。
说到灾难我就想起郑州暴雨，想不到也已经过了好几年。我印象最深刻的事情就是应急管理部派出了救灾无人机，飞到灾区建立通信。
因为当年汶川地震的时候，通信是一个大问题，要靠空降兵舍生忘死跳伞进去，这样一对比，是不是进步很多？

正反两面的话都说完了，我应该给《常识》什么评价呢？我都有点觉得自己像是寓言里面的蝙蝠，
聪明的蝙蝠可以在鸟兽两边占便宜，但是当蝙蝠在今天这种丛林的环境里面更多会被鸟兽两边暴打。

我在这里就不给出评价，在这个大传播的时代，一个廉价的评价没有什么意义。我甚至有一段时期有个暴论就是其实不读书都行。
那我在这里谈《常识》这本书又有什么意义呢？爱因斯坦有句名言：所谓的常识，就是人到十八岁为止所累积的各种偏见。
重要的不是《常识》这本书讲了什么，而是我们能不能超越时间背景去审视被成为常识的事情。
