#+TITLE: 如果在冬夜，一个旅人：原神，启动！

我这个节目很少讲经典书籍，主要是因为我觉得自己经师不名学艺不周，水平不够，讲不了经典的书。但今天我要讲一本二十世纪的不朽经典，就是意大利作家卡尔维诺的作品《如果在冬夜，一个旅人》。

为什么我要不自量力讲这本书呢？很简单，要蹭热度，《原神》月之四版本的名字就是《如果在冬夜，一个旅人》，就是引用了这部经典小说，我要蹭这个热度。说句题外话，《原神》这个游戏里面有很多很文学的梗，有机会我可能会做一期节目。

回到正题，这本《如果在冬夜，一个旅人》在国内有另外一个译名叫《寒冬夜行人》。这部小说很奇特，它是用第二人称写了，一直以「你」称呼本书的叙事主体，我这里说叙事主体是因为这个「你」在中途换过一两次。最初的时候，主角是一个男读者，
这个男读者在整本书里面是没有名字的，他去书店买了一本叫《如果在冬夜，一个旅人》的书，回家读了个开头，发现出现印刷错误，这本书全都是一个印张，一个印张就是16页，就是从第17页开始又是从第1页开始。于是第二天他就去书店要求换书，他遇到了一个有同样问题的女读者，柳德米拉。
书店卖了一本错误的书给他，书店老板给了他另外一本书。于是他跟柳德米拉相约一块读这本新书，但是，意外又来了，这本新书也是有问题的！在整个故事里面，男女读者追逐着一本又一本开了头但戛然而止的书，就像 Rick and Morty 这部动画里面，Rick 和 Morty 两爷孙穿越一个又一个传送门一样。

读完这本书之后，我忽然有一个问题，《如果在冬夜，一个旅人》这本书里面讲了多少个故事呢？第一反应当然是10个，因为男读者在里面读了10本只有开头的书，但是稍微仔细一想，至少有十一个故事，因为男读者遇到柳德米拉，追逐那些书的过程本身就是一个故事。沿着这个思路往下面想，
我们可以发现书中有更多的故事，比如第六章男读者去到出版社询问出版错误的问题，他看到一个翻译家马拉纳给出版社写的信。这些信里面讲了一个又一个光怪陆离的故事，一会被革命党绑架，一会阻止王妃政变。而且啊，我要提醒读者们，「A给B讲了一个故事X」这么一个概括里面可能就包含两个故事，
X本身以及A给B讲故事这件事，就像我们小学时候那种数三角形的题目，小三角形可以组成大三角形，几个小三角形反复组合可能可以输出二三十出来。或许就像书里第七章的故事提到的万花筒一样，稍微把镜子一转，一个新的图案就出来了，我们可以创造出无数个图案——说到无限，就有点博尔赫斯的味道了。

如果你的阅读经验不够多，读到后面几章可能会觉得很混乱，甚至可能觉得不知所谓，或者你从来都不是一个爱读书的人，但无论如何，我都推荐你读完第一章。接下来我会读一部分原文。

你即将开始阅读伊塔洛·卡尔维诺的新小说《如果在冬夜，一个旅人》​。先放松一下，然后集中注意力。抛掉一切无关的想法，让周围的世界隐去。最好关上门，隔壁老开着电视。立即告诉他们：​“不，我不要看电视！”大声点，否则他们听不见。​“我在看书！不要打扰我！”
也许那边噪音太大，他们没听见你的话，你再大点声，怒吼道：​“我要开始看伊塔洛·卡尔维诺的新小说了！”你要是不愿意说，也可以不说；但愿他们不来干扰你。

找个最舒适的姿势吧：坐着、仰着、蜷着或者躺着。仰卧、侧卧或者俯卧。坐在安乐椅上、长沙发上、摇椅上、躺椅上、睡椅上。躺在吊床上，如果你有吊床的话。当然也可以躺在床上，或者躺在被窝里。你还可以头朝下拿大顶，像练瑜伽功。当然，书也得倒过来拿着。

是啊，理想的阅读姿势是找不到的。过去人们曾站在阅读架前看书，习惯站着。他们习惯站着不动。骑马骑累了，他们就那样站着休息。以前还从来没人想到骑在马上看书；可今天，骑坐在马鞍上看书，把书放在马背上或者用特制的马具把书挂在马耳朵上，好像对你挺有吸引力。
两足插在脚镫里看书应该是个非常舒适的姿势。要从阅读中得到享受，首要的条件就是把两只脚抬起来。

这是写读书前的准备的。

你把书捧在手里翻过来转过去地看，看看护封与封里上的文字，都是些一般的话，没有多大意思。对呀，任何封皮上的话都不能越俎代庖，不能告诉你应该由书本直接告诉你的东西，也不能代替你将从书中汲取的东西(尽管你可能受益匪浅也可能受益不大)。
当然，把刚买来的书拿在手里反复看看外表，读书本的内部之前先读读它的外部，也是新书能带给人的一种乐趣。然而一切起初的快感都有个最佳时限，如果想使它变成一种持久的快乐，亦即阅读的快乐，就应掌握好这个时限。

喏，你现在已准备好开始看第一页前几行了。你希望立即能看出作者独特的风格。遗憾，你没看出来。你又仔细想想，谁说这位作家有种独特的风格呢？恰恰相反，大家都知道，他的每一本书都不相同。他的独特性就是他的多变性。
他的这部小说仿佛与他至今所写的所有小说毫不相同，至少与你能回忆起来的他的那些小说不同。你感到失望？等着瞧吧。开始时也许你感到有点晕头转向，犹如你看到一个人，他的名字使你想到一种长相，可是你看到的相貌与你记忆中的长相对不上号。
你往下看，觉得这本小说尽管不符合你对作者的期望，但还可以读，它引起了你的兴趣。如果你再细想想，会觉得这样更好。如果要你选择，你会选择这本你还说不出个子午卯酉的书。

我为什么读着两段呢，讲一个故事，我以前都对北京烤鸭不感兴趣，直到我听了郭德纲几个讲到吃烤鸭的相声，绘声绘色之下我才觉得烤鸭有意思，才开始去尝试不同饭店的烤鸭。同样的，卡尔维诺这里把阅读之乐写得惟妙惟肖，
我相信也能吸引更多的人走进阅读。
