#+TITLE: 睡觉的笨蛋：baka 的气质
#+AUTHOR: Dantezy <zhangyet@gmail.com>
#+HTML_HEAD: <link rel="stylesheet" href="https://latex.now.sh/style.css">
#+OPTIONS: ^:nil
今天给大家介绍我最喜欢的漫画家石黑正数的作品《睡觉的笨蛋》。

它讲的故事很简单，住在一间简陋宿舍的学姐鲸井和学妹入巢的日常故事。
鲸井是玩乐队的，这本漫画的标题 ネムルバカ ，是用片假名写的，以我对日文粗浅的认识相当于用拼音写了书名。
ネムルバカ 是书中主角学姐创作的一首歌。入巢会比较空虚一点，每天去打打工，有点浑浑噩噩的样子。
当然最后两人的生活还是有个大改变，鲸井终于收到音乐公司递来的橄榄枝。故事的结局我就不剧透了。

这部漫画去年改编成电影，出演入巢的是乃木板48三期的久保史绪里，出演鲸井的是平祐奈，
她在豆瓣的照片我觉得有点想新垣结衣。两个主演都是美女，那电影跟漫画的气质就截然不同了。

前面我们说过森见登美彦的《有顶天家族》，还有《海贼王》里面的御田，
「那是傻瓜的血脉使然啊」，塑造了一种「傻瓜」气质，能不能接受当然是另外说。
石黑正数作品就有一种 baka 的气质——这里我遵循唐代玄奘法师「五不翻」的原则，不把 baka 翻译成「笨蛋」。
因为石黑正数笔下的角色并不是不聪明，像《女仆咖啡室》的女主岚山步鸟，她经常能做出很漂亮的推理，
但是却对自己青梅的暗恋视而不见，有时候还会弄巧成拙，再配合石黑正数经典的大饼脸，
你如何看漫画你会明白这种微妙但是难以言传的 baka 气质。

所以电影选了两个美女来演，气质就完全变了，鲸井变得疲惫，而入巢变得高冷，没有漫画里面那种轻盈的 baka 气质。
虽然如此，我不是说这部电影不同，大家还是可以看看这部电影，它跟漫画剧情差不多，一个又一个小故事，
可以随时看随时放下。

这部漫画讲的故事其实描绘了青年的困境，鲸井的困境是知道自己要做什么，
但是觉得自己已经到了一个难以跨越的障碍前面。入巢的困境是没有目标，不知道自己想做什么。
这个困境首先不单纯是她们的问题，我们都知道日本「失去的三十年」这个说法。
甚至我们现在去观察国内的舆论，我们甚至可以说这不止是日本年轻人的问题。
可能现在整个世界所有没有直接卷进战争的年轻人都会有这种问题。

那最后作品给出答案了吗？我很严肃地说，没有，也不应该有。由复杂的社会和个人因素综合造成的问题，
都不应该有一个能简而言之的回答。这部漫画最后只是展示了鲸井的奋力一跃，她最终可以说打破了自己的障，
也让入巢走出了虚无。但这个答案通用吗？我不觉得这是一个通用的答案，
一部漫画也不负责对一个复杂的问题提出一个通用的答案。

之前讲森见登美彦的《有顶天家族》，里面有句台词，或者说口号，叫「有趣即正义」。
我觉得石黑正数更高明一点，他不喊口号，但其实里面的角色活得更率性随心。
我讲一个里面的支线小故事，不算很严重的剧透。虽然本来这漫画也不跑剧透。

里面入巢去了鲸井乐队的 live 演出之后喝大了，第二天宿醉翘课。她就觉得自己很堕落。鲸井见她这样就邀请她去玩传接球游戏。
鲸井乐队名气不大，所以表演收入也不多，接了一个外包的活，帮富人家的佣人擦一些铜像之类的饰品，入巢也去帮忙了。
擦完之后两人去了公园玩球，公园里面有个老头在打高尔夫。入巢一用力，球抛太高了就砸中了打高尔夫球的老头，

如果是你，你扔的球砸中人了，你会怎么做？大概率要么去道歉，要么赶紧溜。入巢的第一反应就是砸中人了，我得去道歉。
但是鲸井一把拉住了她，等被砸中的老头站起来怒吼说「球砸到我了」，鲸井就闪出来，骂了老头一顿，说「我要替天行道！」，
然后就拉着入巢跑了。当然，漫画有个特写，公园里面有个牌子说禁止打高尔夫球的，而且鲸井也是等老头站起来没啥大碍才跑，
在道德上不算很冒犯。这个故事我在这里说或者写成轻小说都没有什么意思，漫画随作者的创意，可以展现最有意思的画面和表情，
往往能表达语言难以概括的趣味。欢迎大家看一下这部《睡觉的笨蛋》。
