#+TITLE: 睡觉的笨蛋：baka 的气质
#+AUTHOR: Dantezy <zhangyet@gmail.com>
#+HTML_HEAD: <link rel="stylesheet" href="https://latex.now.sh/style.css">
#+OPTIONS: ^:nil
今天给大家介绍我最喜欢的漫画家石黑正数的作品《睡觉的笨蛋》。

它讲的故事很简单，住在一间简陋宿舍的学姐鲸井和学妹入巢的日常故事。
鲸井是玩乐队的，这本漫画的标题 ネムルバカ ，使用片假名写的，以我对日文粗浅的认识相当于用拼音写了书名。
ネムルバカ 是书中主角学姐创作的一首歌。入巢会比较空虚一点，每天去打打工。
当然最后两人的生活还是有个大改变，鲸井终于收到音乐公司递来的橄榄枝。故事的结局我就不剧透了。

这部漫画去年改编成电影，出演入巢的是乃木板48三期的久保史绪里，出演鲸井的是平祐奈，
她在豆瓣的照片我觉得有点想新垣结衣。两个主演都是美女，那电影跟漫画的气质就截然不同了。

前面我们说过森见登美彦的《有顶天家族》，还有《海贼王》里面的御田，
「那是傻瓜的血脉使然啊」，塑造了一种「傻瓜」气质，能不能接受当然是另外说。
石黑正数作品就有一种 baka 的气质——这里我遵循唐代玄奘法师「五不翻」的原则，不把 baka 翻译成「笨蛋」。
因为石黑正数笔下的角色并不是不聪明，像《女仆咖啡室》的女主岚山步鸟，她经常能做出很漂亮的推理，
但是却对自己青梅的暗恋视而不见，有时候还会弄巧成拙，再配合石黑正数经典的大饼脸，
你如何看漫画你会明白这种微妙但是难以言传的 baka 气质。

所以电影选了两个美女来演，气质就完全变了，鲸井变得疲惫，而入巢变得高冷，没有漫画里面那种轻盈的 baka 气质。
虽然如此，我不是说这部电影不同，大家还是可以看看这部电影，它跟漫画剧情差不多，一个又一个小故事，
可以随时看随时放下。

这部漫画讲的故事其实描绘了青年的困境，鲸井的困境是知道自己要做什么，
但是觉得自己已经到了一个难以跨越的障碍前面。入巢的困境是没有目标，不知道自己想做什么。
她们的困境在日常的生活中展现。那最后作品给出答案了吗？我很严肃地说，没有，也不应该有。由复杂的社会和个人因素综合造成的问题，
都不应该有一个能简而言之的回答。这部漫画最后只是展示了鲸井的奋力一跃，她最终可以说打破了自己的障，
也让入巢走出了虚无。但这个答案通用吗？我不觉得这是一个通用的答案，一部漫画也不负责回答复杂的问题。
