#+TITLE: 鸟有什么好看的：当 Otaku 成为鸟类学家
#+AUTHOR: Dantezy <zhangyet@gmail.com>
#+HTML_HEAD: <link rel="stylesheet" href="https://latex.now.sh/style.css">
#+OPTIONS: ^:nil

在这里先给大家拜个晚年，祝大家晚年快乐！写稿的时候还是初五迎财神的时候。
当然节目上线的时候春节假期也过了，我强烈建议春节假期到元宵之后。

可能大家不知道，我从去年开始有个新爱好，就是观鸟。一月份我每个休息日都出去观鸟，
晒得像古天乐似的。春节假期在家没事做我还吭哧吭哧整了个观鸟的公众号。
所以今天给大家介绍的，是日本鸟类学家川上和人的书，《鸟有什么好看的》。
这本书的日文名字直译过来叫《别因为我是鸟类学家就以为我喜欢鸟类》。

这是一种什么气质呢。这是一种 Otaku 会成为「傲娇」的气质。对的，川上和人也是一个 Otaku。

全书最吸引我的就是他那种 Otaku 的气质。我举一个例子：

#+BEGIN_QUOTE
顾名思义，红头黑林鸽长了个红脑袋。看到这儿，大家大概都会冒出这样一个问题：
为什么它的头是红色的呢？

红色是「红色彗星」夏亚·阿兹纳布尔的专利。他驾驶着采用红色涂装的专用机体，
是宇宙世纪的红色代言人。一看到他的机体，友军便会士气高涨，
而敌军只好诅咒自己的霉运，化作宇宙的尘埃。我谨在此向夏亚致敬，并通过他来探索红脑袋的秘密。
#+END_QUOTE

这是第三章讲保护小笠原群岛上的红头黑林鸽(red-headed wood pigeon, Columba janthina nitens)
他就玩了一个高达里面的梗，夏亚是高达这个系列动画里面最经典的一个反派。全书这种用 ACG 梗的地方比比皆是啊。
所以我说川上老师是一个 Otaku。

可能有些朋友会问，Otaku 不就是死宅吗？死宅居然还能成为要野外调查的鸟类学家？有一本我去年读过但还不确定会不会做一期节目的书
《阿宅，你已经死了！》，里面就提到，Otaku 也就是御宅族这个群体，其实也是分世代的，
作者冈田斗司夫在里面粗略地区分了三个世代，我在这里简单地说一下，第一个世代，

#+BEGIN_QUOTE
要当御宅，就要把喜欢动画、
喜欢电玩或喜欢漫画等事情都不只当成是『自己的兴趣』，而是要当成自己人格形成与为人修行的道场
#+END_QUOTE

非常隆重，是一种贵族主义，而第二世代，是一群精英主义的人，他们会拼命去宣传御宅亚文化，努力去扩圈。
到了第三世代呢？

#+BEGIN_QUOTE
因为第三世代的人们，这群以『萌』为中心的御宅，他们承认自己心中的软弱，他们只想找个忘却现实的逃避场所。
#+END_QUOTE

与此同时，因为信息差的缘故，到了中国大规模接受御宅文化的时候，已经是第三代御宅占据主舞台了，
所以中国人对御宅的印象也就以「废萌」的第三代御宅为主了。当然这点不是很重要，
我想说的是川上和人是属于第一或者第二代御宅的，他身上洋溢着那种战后勃发的生命力，
所以可以熬过在荒岛上做调查的艰难险阻——这段经历就是第二章的主要内容，这一章讲他前往无人的南硫磺岛做调查，
其中的艰难险阻，虽然他以一种轻松愉快的笔调写出来了，但仔细一想都明白个中的艰苦，如果想不到，可以想想熬太线。

说了那么多，我选这本书，主要有两个原因：第一是我沉迷观鸟，第二是我本人多少也沾点宅气，跟作者臭味相投。
单纯论书本身，其实挺一般的。如果当科普看，那信息密度低了点。如果当散文看，前后几章都不挨着，这个锅编辑也是要背的。
但是它很好读，这种好读来自同样宅文化薰陶下产生的熟悉感，通俗点讲就是「都哥们儿」，
从这个角度去拔高的话，我们还是要搞点文化输出，找到更多有共同爱好的人，这样会更好讲故事。
如果单纯对观鸟感兴趣，我推荐大家先在小红书搜一下本地的观鸟活动，这种活动最重要的事情就是亲身实践。
当然也可以关注我的公众号：Dante 的观鸟小屋。对应的文章已经贴到 Shownotes 里面了。
