(use-modules (srfi srfi-1))
(use-modules (ice-9 i18n))

(define script-dir (dirname (current-filename)))
(load (string-append script-dir "/chap02_02.scm"))

(define (random-polynomial)
  (define degree (+ 1 (random 10)))
  (define x (+ 1 (random 100)))
  (let loop ((i 0) (cs '()))
    (if (= i degree)
        (list x (reverse cs))
        (loop (+ i 1) (cons (random 100) cs)))))

(define (time-it proc n)
  (let ((start (get-internal-real-time)))
    (do ((i 0 (+ i 1)))
        ((= i n))
      (proc))
    (/ (- (get-internal-real-time) start)
       1.0
       internal-time-units-per-second)))

(define n-cases 10000)

(display "Generating cases...")
(newline)
(define cases (map (lambda (i) (random-polynomial))
                   (iota n-cases)))

(define case-file (open-output-file (string-append script-dir "/poly-cases.txt")))
(for-each (lambda (c) (write c case-file) (newline case-file)) cases)
(close-port case-file)
(display "Cases written to poly-cases.txt")
(newline)

(define (run-horner case)
  (horner-eval (car case) (cadr case)))
(define (run-poly case)
  (poly-eval (car case) (cadr case)))

(display "Running horner-eval...")
(newline)
(define h-time (time-it (lambda () (for-each run-horner cases)) n-cases))
(display "Horner-eval time: ")
(display h-time)
(display " s")
(newline)

(display "Running poly-eval...")
(newline)
(define p-time (time-it (lambda () (for-each run-poly cases)) n-cases))
(display "Poly-eval   time: ")
(display p-time)
(display " s")
(newline)

(let ((ok #t))
  (for-each (lambda (case)
              (let ((h (run-horner case))
                    (p (run-poly case)))
                (if (not (= h p))
                    (begin (set! ok #f)
                           (display "Mismatch: x=")
                           (display (car case))
                           (display " coeffs=")
                           (display (cadr case))
                           (display " horner=")
                           (display h)
                           (display " poly=")
                           (display p)
                            (newline)))))
             cases)
  (display "All results match: ")
  (display ok)
  (newline))
