* PERMANENT Memory                                               :BPF:memory:
  CLOSED: [2021-11-14 日 15:12]
** PERMANENT Background
   CLOSED: [2021-11-07 日 01:26]
*** PERMANENT memory allocator
    CLOSED: [2021-11-06 六 20:20]
 libc 的内存创建出来之后，会保存在堆里。申请的内存被释放之后，libc 只会把它标识为可用。当堆的空间不够时，libc 会扩大堆，一般不会缩小堆。

 kernel 和处理器通常都用页来管理内存。kernel 会使用 slab allocator —— 高速缓存。
*** PERMANENT pages and swapping :brk:mmap:page_fault:RSS:kswapd:swapping:mmu:
    CLOSED: [2021-11-06 六 23:22]
内存页的生存周期：

1. 应用申请内存（如 ~mallco()~ ）;
2. 如果有足够的空间，直接分配，如果没有扩大虚拟内存，或者使用 [[file:~/Repos/passenger/notes/tlpi/chap07.org::*~brk()~%20%E5%92%8C%20~sbrk()~][brk()]] 扩大堆的空间，或者使用 [[file:~/Repos/passenger/notes/tlpi/chap49.org::*%E5%86%85%E5%AD%98%E6%98%A0%E5%B0%84][mmap()]] 创建新的内存段（[[file:~/Repos/passenger/notes/wiki/mmap.org::*%5B%5Bhttps://en.wikipedia.org/wiki/Mmap%5D%5Bmmap%5D%5D][mmap 会用在某些 malloc 调用中]]）；
3. 应用尝试使用内存，MMU（将虚拟内存地址转换成物理内存），[[file:~/Repos/passenger/notes/wiki/mmu.org::*%5B%5Bhttps://en.wikipedia.org/wiki/Memory_management_unit%5D%5Bmmu%5D%5D][MMU]] 发现虚拟内存地址还没有映射，会出发 page fault;
4. 内核捕捉到 [[file:~/Repos/passenger/notes/wiki/page_fault.org::*%5B%5Bhttps://en.wikipedia.org/wiki/Page_fault%5D%5Bpage%20fault%5D%5D][page fault]]，创建映射，扣减 [[file:~/Repos/passenger/notes/wiki/rss.org::*%5B%5Bhttps://en.wikipedia.org/wiki/Resident_set_size%5D%5BRSS%5D%5D][RSS]];
5. 如果有太多的内存请求，内核会使用 page-out 进程(kswapd)释放一部分页面：a) 从硬盘读取没有被修改的文件系统页，直接释放；b) 被修改过的文件系统页，在释放之前必须被写回去； c) 应用内存页，如果有 swap 设备，那么这些内存页会先被写到 swap 设备。写入 swap device 就是 swapping.
*** PERMANENT page-out daemon                                        :kswapd:
    CLOSED: [2021-11-07 日 00:56]
kswapd 会定期扫描释放，它会在可用内存处于低水位的时候被唤醒。通常不会影响程序性能，但是如果到达 min page 阈值，那么会 block 进程，显式请求内存回收。
*** PERMANENT swap device
    CLOSED: [2021-11-07 日 00:56]
Swap device 提供了系统内存耗尽的降级方案。进程还是可以申请内存，但是被用得较少的内存会被移到 swap device ,这会降低程序速度。如果系统没有 swap 机制，内核借助 OOM killer 杀死进程。
*** PERMANENT OOM killer
    CLOSED: [2021-11-07 日 01:18]
OOM killer 是释放内存的极手段，会采用一种启发式方法找到要杀的进程，尽量保证对系统的影响最小。详细的 OOM 逻辑参考 [[file:~/Repos/passenger/notes/understanding_the_linux_virtual_memory_manager/chap13.org::*Out%20of%20Memory%20Management][ULVMM chap13 Out of Memory Management]]。
*** page compaction
系统通过特定的进程将碎片化的可用内存合并起来。
*** FLEETING file system caching and buffering                 :cache:buffer:
Linux 会用空闲内存作为[[https://www.kernel.org/doc/html/latest/filesystems/caching/fscache.html][文件系统缓存]]，启动时这些缓存会被刷掉，所以系统启动的时候可能会因此消耗大量的内存（甚至用光）。
*** PERMANENT 综述
    CLOSED: [2021-11-07 日 01:26]
因为申请内存的事件发生得太频繁了，导致即使是 BPF 程序也会带来可见的性能耗损。我们可以用一些调用频次较低的事件作为观察的窗口：page fault, page out, ~brk()~ 和 ~mmap()~ 等。

如果我们想追踪 ~malloc()~ 的调用者，我们可以抽样调查 CPU 的调用栈，从 CPU 火焰图（此处该有引用）中追踪 ~malloc()~ 的调用栈。
*** PERMANENT 策略
    CLOSED: [2021-11-07 日 01:26]
1. 查 dmesg 日志看系统有没有调用 OOM killer。
2. 查看有没有 swap device，在检查这些 device 是否有 I/O：出现 swap I/O 说明内存压力大；
3. 检查释放内存的情况，如 free.
4. 检查每个进程的内存使用。如 top 和 ps。
5. 检查 page fault 的比例和 stack trace page faults, 这个策略可以解释 RSS 变化。
6. 检查支持 page fault 的文件。
7. 追踪 ~brk()~ 和 ~mmap()~ 的使用。
** PERMANENT Traditional Tools
   CLOSED: [2021-11-14 日 15:12]
*** PERMANENT kernel log                                              :dmesg:
    CLOSED: [2021-11-07 日 23:39]
~dmesg~ 输出的日志中，OOM Killer 会给出形如 `Out of memory: Kill process 23409(perl) score 329 or sacrifice child` 的日志。还会给出系统级别的内存使用量以及 RSS。
*** PERMANENT kernel statistics
    CLOSED: [2021-11-14 日 15:12]
**** PERMANENT swapon                                                  :swap:
     CLOSED: [2021-11-07 日 23:42]
如果 ~swapon~ 没有输出，说明没有配置 swap device, 如果有，会给出挂载点和使用量。
**** PERMANENT free                                                    :free:
     CLOSED: [2021-11-09 二 23:39]
~free~ 给出系统当前已经使用和空闲的内存容量。注意区分 available 列和 free 列，前者表示「可用」的内存（包括文件缓存），后者表示「完全未被使用」的内存。buff/cache 列表示文件系统缓存页。

~free -m~ 用 M 作单位。 ~free -mw~ 用 M 作单位且区分 buffer 和 cache。
**** PERMANENT ps                                                        :ps:
     CLOSED: [2021-11-14 日 13:23]
值得关注的是三列：

1. %MEM 该进程使用的物理内存的比例；
2. VSZ 虚拟内存大小；
3. RSS Resident set size 该进程实际占用的总物理内存；

~ps -eo pid,pmem,vsz, rss~
**** PERMANENT pmap
     CLOSED: [2021-11-14 日 14:29]
~pmap -x pid~ 注意非本用户的进程需要 sudo 权限，这个命令显示被载入的库和文件映射占用的内存。

这个命令太细致了，会列出所有的 mapping，包括起止地点，还有占用的物理内存大小。但是我实在不怎么会用。
**** PERMANENT vmstat                                                :vmstat:
     CLOSED: [2021-11-14 日 15:04]
看 [[file:~/Repos/passenger/notes/man/vmstat.org::*vmstat][man page]] 就好了。
**** PERMANENT sar
     CLOSED: [2021-11-14 日 15:12]
~sar -B 1~ 展示内存页统计。这个工具的统计量比较多，而且难读，本书没有提供足够的理解，需要从 man page 补充。主要关注 fault/s 这个指标，它统计了 page fault 发生的频率。

~sar~ 太复杂了，还是得看 [[file:~/Repos/passenger/notes/man/sar.org::*sar][sar 的 man page]]。
*** SKIP hardware statistics
** FLEETING BPF Tools
*** FLEETING oomkill
安装了 0.12.0-2 版本的 bpfcc-tools， 这个版本的 ~oomkill~ 被命名为 ~oomkill-bpfcc~ 。

这个工具可以监控到进程 A 因为内存需要杀死进程 B ，并记录进程 B 使用了多少内存页，以及触发 OOM 时候的系统负载。

#+BEGIN_SRC c
#!/usr/local/bin/bpftrace

#include <linux/oom.h>

BEGIN 
{
    printf("Tracing oom_kill_process()... Hit Ctrl-C to end.\n");
}

kprobe:oom_kill_process // ? what is a kprobe
{
    $oc = (struct oom_control *) args1; // ? how to invoke an struct
    time(%H:%M:%S);
    printf("Trigger by PID %d (\"%s\"), ",  pid, comm); // ? where did pid and comm come from
    printf("OOM kill of PID PID %d (\"%s\"), %d pages, loadavg: ", 
        $oc->chosen->pid, $oc->chosen->comm, $oc->totalpages);
    cat("/proc/loadavg");
    
}
#+END_SRC

~oom_kill~ 主要就是监控 ~kprobe:oom_kill_process~ , ~oom_kill_process()~ 的第二个参数是 ~struct oom_control~ 这个结构体有被牺牲进程的细节。
*** FLEETING memleak
首先这个工具的名字也有变化： ~memleak-bpfcc~.

然后 ~memleakbpfcc -p 556~ 可以只监控进程556的情况。

看不太懂它的输出。
*** SKIP mmapsnoop
(ubuntu 上 0.12.0-2 的 bpfcc-tools 找不到这个工具)。
*** FLEETING brkstack
追踪 ~brk()~ 以追踪程序堆的增长。

~trace-bpfcc -U t:syscalls:sys_enter_brk~ 会输出 PID, TID, COMM, FUNC 四列。

~stackcount-bpfcc -PU t:syscalls:sys_enter_sbrk~ 会列出调用 ~brk()~ 和 ~sbrk()~ 的调用栈和调用次数。但是有时候它会断掉，我们无法追踪具体的调用链。

~brk()~ 调用的频率不高，所以跟踪它往往比跟踪 ~malloc()~ 划算。

~brkstack()~ 的 bpftrace 实现。

#+BEGIN_SRC c
#!/usr/local/bin/bpftrace

tracepoint:syscalls:sys_enter_brk
{
    @[ustack, comm] = count(); // ? what grammer
}
#+END_SRC
*** SKIP shmsnoop
用于 System V 所以我们跳过。
*** FLEETING faults
跟踪页错误的意义在于：页错误会导致 RSS 增长，它可以解释进程占用的内存为什么增长。

常用的 one-liner:

~stackcount-bpfcc -U t:exceptions:page_fault_user~

~stackcount-bpfcc -U t:exceptions:page_fault_kernel~

bpftrace 实现：

#+BEGIN_SRC c
#!/usr/local/bin/bpftrace

software:page-faults:1 // ? what does 1 mean?
{
    @[ustack, comm] = count();
}
#+END_SRC

