#+TITLE: 第三课
#+OPTIONS: ^:nil
#+HTML_HEAD: <link rel="stylesheet" href="https://latex.now.sh/style.css">
* 成语
** 迫不及待
*急迫得不能等待。形容心情急切*
*** 出处
#+BEGIN_QUOTE
德宗不许李惟岳之嗣位而乱起，延及数年，身几危，国几亡，天下鼎沸，
是岂可谓德宗之宜听其嗣，使假我之爵位，据我之土地甲兵以抗我哉？
而不许之，则又兵连祸结而不解。论者至此而议已穷，谓不先其本，而急图其末，是已。
顾处此迫不及待之势，许不许两言而判，徒追咎于既往，而无以应仓卒，是亦尘羹土之言耳。

————王夫之《读通鉴论》[fn:1]
#+END_QUOTE
*** 例句
#+BEGIN_QUOTE
他迫不及待地想和在外地工作的哥哥见面。
#+END_QUOTE
** 七嘴八舌
*形容人多嘴杂，其说不一；也形容饶舌，多嘴。*
*** 出处
#+BEGIN_QUOTE
名教中人《好逑传》[fn:2]第五回：“众人正跑得有兴头上，忽被铁公子拦住，便七嘴八舌地乱嚷。”
#+END_QUOTE
*** 例句
#+BEGIN_EXAMPLE
球迷们一面看足球比赛，一面七嘴八舌地议论着。
#+END_EXAMPLE
** 齐心协力
*认识一致，共同努力。*
*** 出处
#+BEGIN_QUOTE
《墨子·尚贤》[fn:3]：“《汤誓》曰：‘聿求元圣，与之戮力同心，以治天下。’”
#+END_QUOTE
*** 例句
#+BEGIN_EXAMPLE
拔河比赛最讲究齐心协力。
#+END_EXAMPLE
* 阅读材料

#+BEGIN_QUOTE

南阳地方的宋定伯年轻的时候，（有一天）夜里走路遇见了鬼，又问道：“谁？”鬼说：“我是鬼。”鬼问道：“你又是谁？”宋定伯欺骗他说：
“我也是鬼。”鬼问道：“你要到什么地方去？”宋定伯回答说：“要到宛市。”鬼说：“我也要到宛市。”他们一同走了几里路。 鬼说：“步行
太劳累，可以轮流相互背负。”宋定伯说：“很好。”鬼就先背宋定伯走了几里路。鬼说：“你太重了，恐怕不是鬼吧？”宋定伯说：“我刚死，
所以身体比较重。”轮到宋定伯背鬼，这个鬼几乎没有重量。他们像这样轮着背了好几次。

宋定伯又说：“我是新鬼，不知道鬼害怕什么？”鬼回答说：“只是不喜欢人的唾沫。”于是一起走。在路上遇到了河水，宋定伯让鬼先渡过
去，听着它一点声音也没有。宋定伯自己渡过去，水哗啦啦地发出声响。鬼又说：“为什么有声音？”宋定伯说：“我刚刚死不久，是不熟
悉渡水的缘故罢了，不要见怪。”一路上，快到宛市，宋定伯便把鬼背在肩上，紧紧地抓住它。鬼大声惊叫，恳求放他下来，宋定伯不再
听他的话。宋定伯把鬼一直背到宛市中，才将鬼放下在地上，鬼变成了一只羊，宋定伯就卖了它。宋定伯担心它再有变化，就朝鬼身上吐
唾沫。卖掉得到一千五百文钱，于是离开了宛县的集市。当时石崇说过这样的话：“宋定伯卖鬼，得到了一千五百文钱。”

——晋 干宝《搜神记》
#+END_QUOTE

* Footnotes
[fn:3] 墨子（前468年？－前376年），子姓，墨氏，名翟，春秋末战国初期宋国（今河南商丘）人，一说鲁国（今山东滕州木石镇）人，是中国著名思想家、科学家、政治家、军事家。
提出了“非儒”、“兼爱”、“非攻”、“尚贤”、“尚同”、“天志”、“明鬼”、“非命”、“非乐”、“节葬”、“节用”、“交相利”等观点，创立墨家学说，并有《墨子》一书传世。

[fn:2] 又名《侠义风月传》，坊本亦名《第二才子好逑传》，是清代名教中人编次小说，4卷18回。

[fn:1] 《读通鉴论》是明末清初大儒王夫之阅读《资治通鉴》及历史的议论。书成于王夫之晚年，盖读史有感，随事触发，
初无意于为文，故每篇皆不立题目；而于上下古今兴亡得失之故，制作轻重之原，均有论列



