#+TITLE: 与 LDS 传教士的经历
#+OPTIONS: ^:nil
#+HTML_HEAD: <link rel="stylesheet" href="https://latex.now.sh/style.css">

* 缘起
我 leader Robin 貌似是个姨粉，他推崇小共同体，基于这种里面，他来新加坡之后就开始找教会，在他的怂恿下，我也参加教会的活动。

我们最初去离我们家两站路的 Queentown 卫理公会教堂（有机会我会谈谈卫理公会）参加礼拜。第一次去的时候他跟我说基督教后期圣徒教会（俗称摩门教，以下简称 LDS），传教很积极，会提供英语课（甚至还有相亲）。

不过他们英语课都是在周二和周四晚上，我并不想参加，但我对 LDS 还是挺好奇的。后来有个周日，我不想去卫理公会的礼拜，于是就去了 LDS 的教堂。

* 初见
第一次去的时候迟到了一点，进了教堂不知道往哪里去，有个女信徒很热心地带我去举办崇拜的场所——大概中学教室大小的房间。里面基本坐满了人。这个信徒很热心地把我带到一个华人传教士旁边。

这个传教士是一个白净的年轻人，二十岁出头，姓林（但传教士都会叫长老，特别丐帮），他的拍档如果我没有记错是来自犹他州的美国人。

LDS 的礼拜跟卫理公会的礼拜不同，卫理公会都是牧师上去布道，LDS 会让信徒上去讲他们信仰的内容，我本来想听完布道就走，但是听完之后传教士拉着我去上主日课。我不好推托，跟着去了（Google Map 上说要上到一点）。主日课上讨论的内容，我记不清了，林长老让我下载 LDS 出的福音图书馆，里面有《摩尔门经》和他们高层的一些布道，我们当天讨论了一篇布道词，我还当众读了一段《摩尔门经》。

上完主日课，林长老要了我的 WhatsApp ，之后我开始频繁跟 LDS 的传教士接触。

* 传教士
认识林长老之后，我们一般会在周二晚上用 Zoom 开一次会（我不知道这叫什么明目）。

LDS 的传教士称为长老，一般都是两个人搭档。长老们的流动性很强，我认识的第一对传教士林长老和 Elder Tyler 跟我开了两次会之后，就被调到三巴旺了，然后换了另外一对传教士马长老（他是新加坡印度裔，我记不住他原本的姓氏了，但每个传教士都会）和 Elder Beson。然后两次会议之后，马长老也走了。换了来自美国的 Elder Stein——我觉得可能 LDS 的传教士产能过剩了，已经找不到本地的传教士跟他们搭档了。

LDS 的传教士每6周会去别的教区，两个人共同一台手机，而且搭档也会轮换。我猜这个制度是防止传教士跟信徒建立个人关系。因为这样轮换几次之后，你都不知道 WhatsApp 后面的传教士是哪个。他们也说过，你们要跟随耶稣，不是跟随传教士。

传教士没有薪水（我猜有生活津贴），日常工作是去传教——上周末给我上完英语课之后他们说要去 Chinatown 传教，我问那边有没有办公室，他们说没有，就是在街上传教，很有可能就是上街拦住路人问「你有没有兴趣听我介绍一下我们的救主耶稣基督？」。除此之外他们还要组织周末的布道。一周只有周一下午可以休息，还要搞卫生，着实辛苦。

上周去上完英语课之后，我跟传教士们说到我是做软件开发的，Elder Beson 问我是不是 C++，还说他也学过 C++，但是现在都写 JavaScript，不知道他有没有上过大学。

* 我的宗教生活
总的来说，在 LDS 这边的宗教生活还是挺愉快的。我觉得这边的教徒和传教士都是真心信教的（或者至少伪装到我看不出有假，像 Robin 就是赤裸裸的功利主义者，上周遇到一个姓彭的中国人，估计没啥兴趣）。我跟虔诚信教的信徒来往的时候常常有一种愧疚感，因为我实在无法相信上帝。

前一周开始，两个传教士就开始问我，能否考虑洗礼，我说现在还不行，因为我还不相信上帝，我不能为了让你们高兴就虚伪地接受洗礼。他们说可以你是对的，但我们可以设一个时间，我们就设在5月28日吧！我说好啊好啊（反正我也不会答应）。

我之后应该还会继续跟 LDS 的传教士和信徒来往的——直到我觉得「非受洗不可」。因为处于被信众包围的时候氛围中，确实很容易有种「要不就信了吧」的感觉。对抗这种氛围就算是对抗洗脑的练习了。
