* ORGANIZING livepatch                                         :livepatching:

** PERMANENT Motivation
   CLOSED: [2021-11-13 六 23:53]
   就是为了不重启打补丁。


** PERMANENT Kprobes, Ftrace, Livepatching                    :kprobe:ftrace:

livepatching 的关键就是 code redirection，就是运行到某一点的时候绕开，运行另一段代码，主要有三种方法：

1. kernel probes: 插一个断点实现 code redirection;
2. function tracer: 从靠近函数入口(function entry point)的地方调用一个预定义的函数，需要打开 gcc 的 ~-pg~ 选项；
3. livepatching 需要在函数参数或者栈改变之前开始作用;

三种方法[fn:1]需要在运行时修改执行的代码。解决 code redirection 问题的方案大部分以动态 ftrace 框架为基础。Kprobe 被注册成 function entry 被探知时执行的 ftrace handler 。 live patch 中的函数也会在定制的 ftrace hanlder 帮助下被调用。
** ORGANIZING Consistency Model                           :consistency_model:
最好的一种 patching 是自洽的：只修改某个函数的逻辑，不影响其他函数，不改变语义。

但是考虑到更复杂的情况：patching 之后的函数会改变锁的顺序，或者改变某些临时结构体的含义并影响其他参数。这个时候，被影响的单位（可能是 thread 也可能是整个 kernel）需要同时用新版本或者同时用旧版本。

Consistency model 就是如何安全地启动 patching（保证都用新版本或者都用旧版本）。

Livepatching 的 consistency model 混合了 kGraft 的 per-task
 consistency 与 syscall barrier switching 和 kpatch 的
 stack trace switching 机制，此外，它还有一些回退机制。

可以的时候 patch 会逐个 task 生效。生效和失效就是进程 patched/unpatched state 的转换。
interrupt handler 和子进程都会继承 patched state.


检查是否可以 patch 的方法主要有三种：

1. 检查 sleeping task ，如果它的栈里面没有被影响的函数，就 patch 它。周期性执行直到全部被 patch，它需要
   [[https://patchwork.kernel.org/project/linux-mm/patch/20200306062845.YlxErhyCr%25akpm@linux-foundation.org/][HAVE_RELIABLE_STACKTRACE]] (这个配置项说明是否有 ~save_stack_trace_tsk_reliable()~ 或 ~arch_stack_walk_reliable()~ 任意
   一个).
2. 使用 kernel exit switch , 这种方法会在进程从 syscall 中退出到 user space/user space IRC/signal 的时候 patch 。
3. 使用 ~klp_update_patch_state()~ patch idle "swapper" task ，因为这种 task 不会退出 kernel。

不支持 ~HAVE_RELIABLE_STACKTRACE~ 的系统就只能使用方法2了。这样可能会有很多进程在退出之前都使用旧版本的函数，如果这些进程一直不退出，那就需要我们手动发信号。特别是 kthreads 。如果没法保证 patch threads ，那么一个不支持 ~HAVE_RELIABLE_STACKTRACE~ 的系统不能认为全面支持 livepatching 。

文件 ~/sys/kernel/livepatch/<patch>/transition~ 标识是否有一个 patch in transition , 同一时间只能有一个 patch in transition. [fn:2]

往 ~/sys/kernel/livepatch/<patch>/enabled~ 写入不同的值就能开关 patch 了。

~/proc/<pid>/patch_state~ 有三个值：-1 没有 patch; 0 in transition; 1 patched;

还有 ~/sys/kernel/livepatch/<patch>/force~ 这个可以解决[fn:2]的问题。但是要慎用。
*** SKIP Adding consistency model support to new architectures
** FLEETING Livepatching Model    
*** ORGANIZING new functions
命名的时候最好跟 patched 前的函数区分一下，也可以定义为静态函数，毕竟需要全局可见。最麻烦的地方在于：万一新函数需要调用一些原来的源代码定义的局部的东西。后面的 [[file:04-elf-format.org::*livepatch ELF format][livepatch ELF format]] 会讲到。
*** FLEETING metadata                         :klp_func:klp_object:klp_patch:
每个 patch 由三层数据结构表示：

1. ~klp_func~ 定义了每个被 patched 的函数。它描述了原来的函数和新实现的函数之间的关系。它包括新函数的名字(string)，运行时，新函数的地址会通过 kallsyms(全局符号表)【此处应有链接】找到。此外，它包括新函数的地址（一个函数指针）[fn:3]。可选的参数是在 kallsyms 数据库里面的位置。
2. ~klp_object~ 在对象中定义了一个包含 ~klp_func~ 的数组。这个对象可能是 vmlinux 也可能是一个 module 名[fn:4]。注意到被 patched 的 module 可能会在 patch 之后载入。
3. ~klp_patch~ 定义了 ~klp_object~ 的数组。只有当所有的符号都在 kallsyms 里面找到，它才会生效。
** FLEETING Livepatch life-cycle
五个基本动作: loading, enabling, replacing, disabling, removing.
*** FLEETING loading                                                 :module:
这里的 loading 应该是指 module loading。 ~klp_enable_patch()~ 会在且仅在 ~module_init()~ 时会调用。这是因为: 1) 只有 module 可以访问 ~klp_patch~ 结构体; 2) patch 出错，可以阻止 module 继续载入。
*** FLEETING enabling
~module_init()~ 调用了 ~klp_enable_patch()~ 之后，livepatch 进入 enabled 状态。

第一步：根据新函数的名字找到函数地址，并创建 ~/sys/kernel/livepatch/<name>~ 文件。如果这一步失败了，patch 失败。

第二步：livepatch 进入 transition 状态。原始函数第一次被 patch 的时候，系统会创建一个特别的结构 ~klp_ops~ 并注册一个 ftrace handler（注意同一个函数可能会被 patch 多次，但是 handler 只会注册一次，更多的 entry 就在列表后面增加一个就好了）。并且会在 ~/sys/kernel/livepatch/<name>/transition~ 里面写入1。

第三步：所有 task 都已经 patch， ~/sys/kernel/livepatch/<name>/transition~ 写入0.
*** FLEETING replacing                                              :TO_LINK:
看起来是用一个 livepatch 替换另外一个，后面会详细说。
*** FLEETING disabling
通过往 ~/sys/kernel/livepatch/<name>/~ 里面写0 disable 一个 livepatch.

首先，livepatch 进入 transition 状态。然后等所有 task 都回退之后， ~/sys/kernel/livepatch/<name>~ 写入0。 ~klp_ops~ 也要进行清理。最后 ~/sys/kernel/livepatch/<name>~ 也会被清理。
*** FLEETING removing
强制 patch 不可取之处在于它导致 module 无法安全 remove。
** FLEETING Sysfs                                                     :sysfs:
都在 ~/sys/kernel/livepatch~ 下面了。

整理的时候整理下对应的表吧。
** FLEETING Limitation

1. 只有能被 trace 的函数才能被 patch。另外它不能递归 patch.
2. 只有 ftrace 是在函数开头起作用，patch 才是可靠的。
3. kretprobe 跟 patched function 冲突。
4. 原函数中的 kprobe 会被忽略，因为函数被 redirect 了。

* Footnotes

[fn:4] 这给我整不明白了，为什么 module name 可以跟 vmlinux 放在一起说啊。 

[fn:3] 前面不是说要从 kallsyms 里面找了吗？ 

[fn:2] 如果有两个 patch 要打，前面一个就死活卡在 in transition ，我们是不是只能杀进程了？ 

[fn:1] 但其实我觉得这并不是「三种方法」，就我理解，livepatching 使用 kprobes 和 ftrace 实现的。当然这个理解可能是错的。
